### ISSUE TITLE
Problem with large notifications

### ISSUE THREAD

**Issue by FilmjunkieGF** [bjoerns1983/Emby.Plugin.TelegramNotification#4]
Hello,

when you have a lot of media content added (more than one telegram message, the limit for one message is 4096 characters) the plugin wont post anything and shows this error in logs:

2019-12-12 14:38:46.492 Error NotificationManager: Error sending notification to Telegram Notifications
	*** Error Report ***
	Version: 4.3.0.30
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Unix 4.15.0.70
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Runtime: file:///opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 12
	Program data path: /var/lib/emby
	Application directory: /opt/emby-server/system
	MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: BadRequest
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
	   at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
	   at Emby.Plugin.TelegramNotification.Notifier.SendNotification(UserNotification request, CancellationToken cancellationToken)
	   at Emby.Notifications.NotificationManager.SendNotification(NotificationRequest request, INotificationService service, String title, String description, User user, CancellationToken cancellationToken)
	Source: Emby.Server.Implementations
	TargetSite: Void MoveNext()

**Comment by bjoerns1983** [comment]
Jep i already noticed that.
Maybe i have the chance during the holidays to resolve that.

**Comment by FilmjunkieGF** [comment]
Any update on this?

**Comment by bjoerns1983** [comment]
Unfortunately not but you are welcome to send in a PR.

**Comment by bjoerns1983** [comment]
Message splitting is now integrated
